baseURL: https://longis.me/
languageCode: en-us
title: Long's Blog
theme: hello-friend-theme
paginate: 100
disqusShortname: longis-me
enableRobotsTXT: true

params:
  title: Long's Blog
  description: Long writes about software engineering and technologies
  contentTypeName: posts
  defaultTheme: light
  showReadingTime: true
  googleAnalyticsID: "G-111E3ZFMZL"

languages:
  en:
    params:
      logo:
        logoText: longis.me
    menu:
      main:
      - identifier: about
        name: About me
        url: /about
      - identifier: kofi
        name: Buy me a coffee
        url: https://ko-fi.com/longisme
      - identifier: archive
        name: Archive
        url: /archive
