baseURL: https://longis.me/
languageCode: en-us
title: Long's Blog
theme: hello-friend
paginate: 100
disqusShortname: longis-me

params:
  contentTypeName: posts
  defaultTheme: light
  showReadingTime: true

languages:
  en:
    params:
      logo:
        logoText: longis.me
    menu:
      main:
      - identifier: about
        name: About Me
        url: /about
